- name: Install packages
  hosts: all
  become: yes
  tasks:
    - name: update cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install pip
      ansible.builtin.include_role:
        name: geerlingguy.pip

- name: Set env file
  hosts: all
  tasks:
    - name: copy env file
      ansible.builtin.template:
        src: ./.env.j2
        dest: ./.env

- name: Deploy app
  hosts: all
  become: yes
  tasks:
    - name: run app in docker
      community.docker.docker_container:
        name: app
        image: redmine
        published_ports: "80:3000"
        restart_policy: always
        restart: true
        pull: true
        env_file: ./.env

- name: Setup Datadog Agent
  hosts: webservers
  become: yes
  vars_files:
    - ./group_vars/webservers/vars.yml
  tasks:
    - name: import role
      import_role:
        name: datadog.dd.agent
  vars:
    datadog_api_key: "{{ dd_api_key }}"
    datadog_checks:
      http_check:
        init_config:
        instances:
          - name: Datadog watch
            url: "http://localhost:80"
            method: GET
    datadog_config:
      log_level: INFO
      dogstatsd_non_local_traffic: true
      bind_host: 0.0.0.0
