app_port: 80

datadog_api_key: "{{ vault_dd_api_key }}"
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: Datadog watch
        url: "http://localhost:{{ app_port }}"
        method: POST
datadog_config:
  log_level: INFO
  dogstatsd_non_local_traffic: true
  bind_host: 0.0.0.0